version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install dependencies
          command: pip install -r req.txt
      - run:
          name: Run tests
          command: python -m unittest discover -s tests  # Adjust the test folder if needed

workflows:
  version: 2
  test-workflow:
    jobs:
      - test

