version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install requests
            pip install -r requirements.txt

      - run:
          name: Run Unit Tests
          command: |
            python -m unittest discover
workflows:
  version: 2
  test_pipeline:
    jobs:
      - build
