version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      # run tests with pytest and coverage
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov=./ --cov-report=xml
      
      # store test results and coverage
      - store_artifacts:
          path: coverage.xml
          destination: coverage-report
      
      - store_test_results:
          path: test-results

