put code "version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use CircleCI's Python image
    steps:
      - checkout  # Check out the source code
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv  # Create a virtual environment
            source venv/bin/activate  # Activate the virtual environment
            pip install -r req.txt  # Install the dependencies from requirements.txt

      - run:
          name: Run Tests
          command: |
            source venv/bin/activate  # Activate the virtual environment again
            pytest testHW04a_API.py --cov=your_project_folder  # Run your tests and collect coverage for your project

workflows:
  version: 2
  test_pipeline:
    jobs:
      - build
